version: '3.8'

services:
  localstack:
    image: localstack/localstack:3
    ports:
      - '4566:4566'
    environment:
      SERVICES: lambda,logs,resourcegroupstaggingapi,cloudformation,s3
      DEFAULT_REGION: us-east-1
      LAMBDA_EXECUTOR: local
      DEBUG: 0
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 5s
      timeout: 5s
      retries: 20
